// <auto-generated />
using ExamenVDG.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExamenVDG.Migrations
{
    [DbContext(typeof(ExamenVDGContext))]
    [Migration("20221024211310_Inicio")]
    partial class Inicio
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Modern_Spanish_CI_AI")
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ExamenVDG.Models.Consola", b =>
                {
                    b.Property<int>("IdTipoConsola")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoConsola"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("IdTipoConsola");

                    b.ToTable("TipoConsola", (string)null);
                });

            modelBuilder.Entity("ExamenVDG.Models.Genero", b =>
                {
                    b.Property<int>("IdTipoGenero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoGenero"), 1L, 1);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(256)
                        .IsUnicode(false)
                        .HasColumnType("varchar(256)");

                    b.HasKey("IdTipoGenero");

                    b.ToTable("TipoGenero", (string)null);
                });

            modelBuilder.Entity("ExamenVDG.Models.Videojuego", b =>
                {
                    b.Property<int>("IdVideojuego")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVideojuego"), 1L, 1);

                    b.Property<short>("Anio")
                        .HasColumnType("smallint");

                    b.Property<byte>("Calificacion")
                        .HasColumnType("tinyint");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTipoConsola")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoGenero")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("IdVideojuego");

                    b.HasIndex("IdTipoConsola");

                    b.HasIndex("IdTipoGenero");

                    b.ToTable("Videojuego", (string)null);
                });

            modelBuilder.Entity("ExamenVDG.Models.Videojuego", b =>
                {
                    b.HasOne("ExamenVDG.Models.Consola", "Consola")
                        .WithMany("Videojuegos")
                        .HasForeignKey("IdTipoConsola")
                        .IsRequired()
                        .HasConstraintName("FK_Videojuego_TipoConsola");

                    b.HasOne("ExamenVDG.Models.Genero", "Genero")
                        .WithMany("Videojuegos")
                        .HasForeignKey("IdTipoGenero")
                        .IsRequired()
                        .HasConstraintName("FK_Videojuego_TipoGenero");

                    b.Navigation("Consola");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("ExamenVDG.Models.Consola", b =>
                {
                    b.Navigation("Videojuegos");
                });

            modelBuilder.Entity("ExamenVDG.Models.Genero", b =>
                {
                    b.Navigation("Videojuegos");
                });
#pragma warning restore 612, 618
        }
    }
}
